# Generated by Django 2.2.3 on 2019-08-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djxero', '0002_xero_secrets_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroProjectsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_user_id', models.UUIDField(help_text='Xero user ID in the Projects API')),
                ('xerouser', models.ForeignKey(help_text='Regular Xero user ID', on_delete=django.db.models.deletion.CASCADE, related_name='prjuser', to='djxero.XeroUser')),
            ],
        ),
    ]
